### ISSUE TITLE
Festplattenabbilder verwalten

### ISSUE THREAD

**Issue by JMGeithain** [hastho/pigeos#1]
i miss 
"Rename image      Abbild auf USB-Lw umbenennen" 
or
"Rename image      Abbild umbenennen"

**Comment by hastho** [comment]
Variante 1) wäre eher ein "Export as..." ToDo:
- Exportnamen abfragen mit Vorgabe "akt. Name"
- vor Überschreiben warnen

Variante 2) Umbenennen eines lokalen Images, ToDo:
- neuer Name darf nicht vorhandenes Image überschreien
- wenn Image akt. eingebunden ist, muss Eintrag .pigeos aktualisiert werden

**Comment by JMGeithain** [comment]
Beides gut.

**Comment by JMGeithain** [comment]
Schön wäre es, wenn der Name des Images als Name der eingebundenen Festplatte übergeben werden könnte.

**Comment by hastho** [comment]
Abbilder können über 'Rename image' in pigeos-config umbenannt werden( wenn sie nicht gemounted sind):
- zuerst von USB importieren via Hard disk menu/Import image,
- umbenennen via Hard disk menu/Rename image,
- ggf. Beschreibung anpassen Hard Disk menu/Edit image,
- nach USB exportieren via Dard disk menu/Export image

Disklabels werden beim Erstellen/Umbenennen gesetzt, aber leider nicht unter GeoManager angezeigt.
